.TH PQ 1
.SH NAME
pq \- jq for protobuf - parse protobuf generically
.SH SYNOPSIS
.B pq
[\fB\-\-fdsets=PATH\fR]
[\fB\-\-msgtype=STRING\fR]
[\fB\-\-stream\fR]
[\fB\-\-force\fR]
.IR [file]
.SH DESCRIPTION
.B pq
parses a compiled protobuf message with .fdset files located in '~/.pq/'
.SH POSITIONAL ARGS
.TP
.BR (OPTIONAL)file\fR
.br
Read message from a file. Default is stdin.
.SH OPTIONS
.TP
.BR \-\-fdsets=PATH\fR
.br
Use alternative fdset dir. Default is '~/.pq/'.
.TP
.BR \-\-msgtype=STRING\fR
.br
Use this message type to decode protobuf - must be a fully qualified message name e.g. 'com.example.dog.Dog'. Default behavior is to try to guess the message type. Guessing and msgtype apply to every message in a stream.
.TP
.BR \-\-stream\fR
.br
Parse varint32-delimited stream.
.TP
.BR \-\-force\fR
Forcefully decode by chopping bytes off the ends. This will apply to every message in a stream.
