.TH PQ 1
.SH NAME
pq \- jq for protobuf - parse protobuf generically
.SH SYNOPSIS
.B pq
[\fB\-\-msgtype=STRING\fR]
[\fB\-\-stream=DELIMITER\fR]
[\fB\-\-trail=DELIMITER\fR]
.SH DESCRIPTION
.B pq
parses a compiled protobuf message with .fdset files located in '~/.pq/'. See more at https://github.com/sevagh/pqrs.

.B pq
operates on stdin by default. Use files with the <filename pipe.
.SH OPTIONS
.TP
.BR \-\-msgtype=STRING\fR
.br
Use this message type to decode protobuf - must be a fully qualified message name e.g. 'com.example.dog.Dog'. Default behavior is to try to guess the message type. Guessing and msgtype apply to every message in a stream.

.B **WARNING 1**:
since protobuf treats fields as positional, similar protos (e.g. Dog: <Int: age, String: breed>, Person: <Int: ssn, String: name>) are indistinguishable.

.B **WARNING 2**:
guessing cannot distinguish between user-specified nulls and empty fields. E.g., if you specify an <Int, String, String> as <5, "hello", null>, pqrs discards the correct schema because of the null.
.TP
.BR \-\-stream=DELIMITER\fR
.br
Parse a delimited stream. The delimiter is specified as a string. For now the only supported delimiter is "varint" (this is the way it's done by Google in delimited_message_util).
.TP
.BR \-\-trail=NUM\fR
.br
Delete NUM number of trailing characters between streamed messages.
.TP
.SH ENVIRONMENT VARIABLES
.TP
.BR FDSET_PATH\fR
.br
Specify alternative fdset path. Default is '~/.pq/'.
